### PR TITLE
67 create interview parser

### PR DESCRIPTION
**Pull request by goalfix**
WIP:
- [x] Create barebone implementation of `addinterviewparser`
- [x] Create implementation of `addinterviewcommand`
- [x] Use the applicant index to actually find the applicant, before creating interview object in `AddInterviewCommandParser`
- [x] Parse the required positions as well
- [x] Check for duplicated interviews (this goes down a long rabbit hole in terms of adding stuff to model)
- [x] Actually add the interview (similar to above)

### CODE REVIEW

**Comment by YiHern-Lee** [comment]
For point 3, could use something similar to line 71-77 in AddCommand:
```
List<Person> lastShownList = model.getFilteredPersonList();

if (index.getZeroBased() >= lastShownList.size()) {
        throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
 }
Person personToEdit = lastShownList.get(index.getZeroBased());
```

1. Retrieve the filtered list from the model
2. Check if index is valid (applicant exists)
3. Pass the applicant to the AddInterviewCommand

**Comment by goalfix** [comment]
Thanks @YiHern-Lee. The issue is that I need this `Applicant` when creating my `Interview` class. See line 44 of `AddInterviewCommandParser`

As such, I don't have access to the `model`, and the interview object needs to be created before passing it to the command portion to be executed.

**Comment by YiHern-Lee** [comment]
@goalfix I believe we can follow the design of EditCommandParser.
1. The parser class itself does not check for the validity of the Person. The parser class only checks if the index is a valid integer that is an integer >= 1.
2. The AddInterviewClass itself can receive the valid index and then attempt to retrieve the applicant from Model. That is where you can check if the Applicant exists at that index.

**Comment by goalfix** [comment]
Thanks @YiHern-Lee for your suggestions. I have solved the issue by reference to the edit command code. One potential issue that I can see from this implementation is that if multiple commands are being run in the same time, causing the relative indexing of `applicants` and `positions` to be changed before the execution of the `addInterviewCommand`. This will cause the wrong applicants and wrong positions to be associated with interview.

However, I think for now it is workable, and we can assume that it runs sequentially. In future iterations, we might want to look into editing both `addInterviewCommandParser` as well as `EditApplicantCommandParser` to solve the issue above. But right now it's working fine :)

**Comment by goalfix** [comment]
@YiHern-Lee Would it be possible for you to implement `ObservableList<Position> getFilteredPositionList();` in the model interface? I will require it in order to parse the position index to match with the correct position for interview. I will create an issue detailing more about this and assign it to you

**Review by SethCKL — APPROVED** [review]
LGTM

Clean and well written code. Thanks for implementing this functionality

**Pull request merged**
